### ISSUE TITLE
Fail to download

### ISSUE THREAD

**Issue by JigaoLuo** [togolife/baidu-wenku-download#5]
```
 1  jigao  ~/workspace/baidu-wenku-download  
> python main.py https://wenku.baidu.com/view/9f23f4ecf605cc1755270722192e453611665b54.html                                                                                               5.1s
Traceback (most recent call last):
  File "main.py", line 105, in <module>
    main()
  File "main.py", line 91, in main
    result = d.down()
  File "/home/jigao/workspace/baidu-wenku-download/downPDF.py", line 51, in down
    res = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden

```

**Comment by sickneet** [comment]
File "main.py", line 70
    print 'Usage:' + os.path.basename(sys.argv[0]) + ' <download file url>'
现在百度文库文档链接和之前格式不一样了

**Comment by JigaoLuo** [comment]
Thanks.
